landing page setup
stock2shop/website pull request #78
Opened 2022-03-24 12:18 UTC by simonious1989

2022-03-24 12:20 UTC, simonious1989 commented
@flumonion I have created one landing page template which may require additional styling.
The example is two columns, text left and form on the right.

2022-03-25 07:43 UTC, flumonion commented
Will make some suggestions/recommendations and commit them to this branch.

2022-03-25 08:16 UTC, flumonion commented
Made some changes.
- shortened url
- made page type descriptive
- changed styling in line with other pages

We should:-
- Create partials for shared code (e.g. artticles and video) this will make it easier to add to other templates in future.
- add name tag to netlify forms.
- ensure we are not duplicate already created form partials.
- remove the word "landing" from the form partial, its just a form and can be included anywhere on site, not specifically for landing pages.

2022-03-25 10:24 UTC, flumonion commented
@simonious1989 forgot to also include a way to add a "do not index" for crawlers on these pages only...

2022-03-25 11:43 UTC, simonious1989 commented
@flumonion 

> Create partials for shared code (e.g. artticles and video) this will make it easier to add to other templates in future.
I have created two new partials:
 - video
 - latest-articles 

> add name tag to netlify forms.
I have updated the form to include a form name. 
Should I do this on the other form partials for consistency?

> ensure we are not duplicate already created form partials.
I did create a new form partial and remove the "text" input.

> remove the word "landing" from the form partial, its just a form and can be included anywhere on site, not specifically for landing pages.
I have done this and renamed it to "quick-contact"

> forgot to also include a way to add a "do not index" for crawlers on these pages only...
I looked into that last night and came across the [following approach](https://github.com/dereckcurry/hugo-robots-meta-tags).
I am not sure if this means we need to go and update all pages now with the suggested front matter.

Also if these pages are not being indexed, we can remove the SEO front matter.

2022-03-28 11:32 UTC, flumonion commented
> Should I do this on the other form partials for consistency?

Yes

2022-03-29 13:14 UTC, simonious1989 commented
@flumonion 

I have added a check in the in the head.html for the `robotsNoFollow` param.
have done a check locally and all other pages without this param are not affected, meaning they still retain:

`<META NAME="ROBOTS" CONTENT="INDEX, FOLLOW">`

All forms now have name tags.
Please could you review and merge.

2022-03-30 06:43 UTC, flumonion requested changes

2022-03-30 06:43 UTC, flumonion commented on themes/s2s/layouts/partials/latest-articles.html
> +<section class="section section--gray section--size4">
In the partial I don't think you should have the wrapper html.
It should only include the cards div onwards.
This means you can list articles in different ways.
i.e. you could have them run across full screen, or smaller etc.

If we wanted to get fancy, we could include [variables](https://gohugo.io/templates/partials/#variable-scoping) in the partials that can be set outside the partial by the page adding the partial. In this example the partial would be in charge of listing articles, the page adding the partial could decide what articles to add.



For example, on one page we could listt

2022-03-30 06:43 UTC, flumonion commented on themes/s2s/layouts/partials/quick-contact.html
> +        <form method="post" name="quick-contact" data-netlify="true">
partial should not have "container" class.

2022-03-30 14:13 UTC, simonious1989 commented on themes/s2s/layouts/partials/quick-contact.html
> +        <form method="post" name="quick-contact" data-netlify="true">
@flumonion I have removed the "container" class from the partial.

2022-03-30 14:45 UTC, simonious1989 commented on themes/s2s/layouts/partials/latest-articles.html
> +<section class="section section--gray section--size4">
@flumonion I have updated this partial and renamed to `article-card.html`
I can refactor everywhere else where this article section is being used on the site now also.

2022-03-30 16:40 UTC, simonious1989 commented
@flumonion 

I have made the following changes:

- created a `call.html` partial 
- updated `quick-contact` partial to remove container class
- used .Scratch to get and set the form name in the lp-form template. (I can change this to rather use a variable so it can be set in the page from matter).
- updated the `article.html` partial 
- updated the contact links on the footer
- updated the lp full form copy

2022-04-12 18:51 UTC, merged